# Generated by Django 4.2.6 on 2023-11-08 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_foro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crearforo',
            old_name='contenido_foro',
            new_name='contenido',
        ),
        migrations.RenameField(
            model_name='crearforo',
            old_name='nombre_foro',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='crearforo',
            old_name='tema_foro',
            new_name='tema',
        ),
        migrations.RenameField(
            model_name='respuestaforo',
            old_name='respuesta_Foro',
            new_name='respuesta',
        ),
    ]
